version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./src/client
      dockerfile: Dockerfile
      args:
        - PORT_CLIENT=$PORT_CLIENT
        - PORT_API_SERVER=$PORT_API_SERVER
    image: devalf/client
    environment:
      PORT_CLIENT: ${PORT_CLIENT}
      PORT_API_SERVER: ${PORT_API_SERVER}
    ports:
      - ${PORT_CLIENT}:80
    volumes:
      - ./src/client:/usr/src/client-app
      - /usr/src/client-app/node_modules

  client-mx:
    container_name: client_mx
    build:
      context: ./src/client-mx
      dockerfile: Dockerfile
      args:
        - PORT_CLIENT=$PORT_CLIENT_MX
        - PORT_API_SERVER=$PORT_API_SERVER
    image: devalf/client_mx
    environment:
      PORT_CLIENT: ${PORT_CLIENT_MX}
      PORT_API_SERVER: ${PORT_API_SERVER}
    ports:
      - ${PORT_CLIENT_MX}:80
    volumes:
      - ./src/client-mx:/usr/src/client-app-mx
      - /usr/src/client-app-mx/node_modules

  server:
    container_name: server
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: devalf/server
    ports:
      - ${PORT_API_SERVER}:${PORT_API_SERVER}
    volumes:
      - ./src/server:/usr/src/server-app
      - /usr/src/server-app/node_modules
    depends_on:
      - mongo-db
    links:
      - mongo-db
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://mongo-db:27017/demo-t2
      - MONGO_DB_USERNAME=${DB_USERNAME}
      - MONGO_DB_PASSWORD=${DB_PASSWORD}
      - PORT_API_SERVER=${PORT_API_SERVER}

  mongo-db:
    container_name: mongo_db
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_DB_USERNAME: ${DB_USERNAME}
      MONGO_DB_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - ./src/mongo-db/data/db:/data/db
      - ./src/mongo-db/scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./src/mongo-db/scripts/products.js:/docker-entrypoint-initdb.d/products.js
