version: '3.7'

services:
  client:
    container_name: client_dev
    build:
      context: ./src/client
      dockerfile: Dockerfile.dev
    image: devalf/client_dev
    ports:
      - '8080:8080'
    volumes:
      - ./src/client:/usr/src/client-app
      - /usr/src/client-app/node_modules

  server:
    container_name: server_dev
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: devalf/server_dev
    ports:
      - '8081:8081'
    volumes:
      - ./src/server:/usr/src/server-app
      - /usr/src/server-app/node_modules
    depends_on:
      - mongo-db
    links:
      - mongo-db
    environment:
      - MONGODB_URL=mongodb://mongo-db:27017/demo-t2

  mongo-db:
    container_name: mongo_dev
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: demo-t2
    ports:
      - 27017:27017
    volumes:
#      - ./src/mongo-db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./src/mongo-db/data/db:/data/db
